server:
  port: 8081
spring:
  application:
    name: "PlazoletaMsFoodcourt"
  devtools:
    add-properties: false
  datasource:
    url: "jdbc:mysql://localhost:3307/plazoleta_foodcourts?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC"
    username: "plazoleta_user"
    password: "plazoleta123"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: "update"
    show-sql: true
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL8Dialect"
        format_sql: true
    databasePlatform: "org.hibernate.dialect.MySQL8Dialect"
jwt:
  secret: "mySecretKeyForJWTTokenGenerationThatIsLongEnoughForHS256Algorithm"
  expiration: 86400000
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
services:
  user:
    url: http://localhost:8080
  traceability:
    url: http://localhost:8082